### ISSUE TITLE
Feature Request: Add Share Option to the individual movie or series

### ISSUE THREAD

**Issue by bhanurp** [ChaitanyaVootla/movie-browser#48]
Add a share button to share this movie or series as themoviebrowser url to share with friends.

**Comment by ChaitanyaVootla** [comment]
![image](https://github.com/user-attachments/assets/57658e4a-f6f3-43f6-a7e3-9ea53bb46bab)
@bhanurp added the share option in the movie description
[commit link](https://github.com/ChaitanyaVootla/movie-browser/commit/17505430b9045ead981ada87688b726f2e35dbb1)

**Comment by bhanurp** [comment]
Awesome 🎉 Thanks
